[project]
name = "app"
version = "0.1.0"
description = "Simplified API for CalDAV via caldav"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "caldav>=3.2.1",
    "fastapi[standard]>=0.136.3",
    "pykit",
]

[tool.uv.sources]
pykit = { git = "ssh://github/axjab/pykit.git" }

[dependency-groups]
dev = [
    "basedpyright>=1.39.10",
]

[tool.ruff.lint]
ignore = ["I001"]
