[project]
name = "app"
version = "0.1.0"
description = "Simplified API for CalDAV via caldav"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "caldav",
    "fastapi[standard]",
    "pykit",
]

[dependency-groups]
dev = [
    "basedpyright>=1.39.10",
]

[tool.ruff.lint]
ignore = ["I001"]

[tool.basedpyright]
typeCheckingMode = "off"

[tool.uv.sources]
pykit = { git = "https://github.com/axjab/pykit.git" }
